READKEY		MACRO
			MOV			AH,	00
			INT			16H
			ENDM
		
SETCRT		MACRO		MODE
			MOV			AH,	00
			MOV 		AL,	MODE
			INT			10H
			ENDM
		
PUTPIXEL	MACRO 		X, Y, WARNA
			PUSH		AX
			PUSH		BX
			PUSH		CX
			PUSH		DX
			MOV			AH,	0C
			MOV			CX,	X
			MOV			DX,	Y
			MOV			AL,	WARNA
			INT			10H
			POP			DX
			POP			CX
			POP			BX
			POP			AX
			ENDM
			
GARISV		MACRO		X1,	Y1,	PANJANG, WARNA
			LOCAL		ULANG
			PUSH 		DX
			MOV			DX,	Y1
			MOV			CX,	PANJANG
	ULANG:
			PUTPIXEL	X1,	DX,	WARNA
			INC			DX
			LOOP		ULANG
			POP			CX
			POP			DX
			ENDM
			
GARISH		MACRO		X1, Y1, PANJANG, WARNA
			LOCAL		ULANG
			PUSH		CX
			PUSH		DX
			MOV			DX,	X1
			MOV			CX,	PANJANG
	ULANG:
			PUTPIXEL	DX,	Y1,	WARNA
			INC			DX
			LOOP		ULANG
			POP			DX
			POP			
			ENDM
			
KOTAK		MACRO		X1,	Y1,	X2, Y2, WARNA
			GARISH		X1,	Y1,	X2-X1, WARNA
			GARISV		X1,	Y1,	Y2-Y1, WARNA
			GARISV		X1,	Y1,	Y2-Y1, WARNA
			GARISV		X1,	Y1,	X2-X1+1, WARNA
			ENDM
			
			.MODEL SMALL
			.CODE
			ORG 100H
			
PROSES:
		SETCRT	13H
		KOTAK	120, 30, 180, 100, 12
		READKEY
		
		SETCRT	03H
		INT 	20H
END 	PROSES
			